### PR TITLE
Allow for column reordering (incl. persisting last order) + sorting the table

### PR DESCRIPTION
**Pull request by Urmel**
* Added new ListViewColumnSorter class
* Extended previous listView read/write column size methods with ordering
* Ensured that all list view items (incl folders & "..") have all sub items
* Changed ".." into constant

Signed-off-by: Alexander Behring <alex@behrings.eu>

### CODE REVIEW

**Comment by Urmel** [comment]
Hi @nemethviktor,
I felt like doing something this evening. One of the smaller things on my list was this...

Any feedback is welcome!
BR
Alex

**Comment by nemethviktor** [comment]
Hi Alex

Awesome, thanks for that - I'll have a proper look today. I think atm there
are 17 outstanding commits sitting on my computer so I'll try to merge this.

Would it be ok if I first finished the time zone change, did a public
release based on the current commits and then merged this? Just so that the
wider public gets and update as well rather than just those that know where
to find the dev releases?

Thanks again, I'll have a look today:)

V



This message has been brought to you by my Huawei P30 Pro and myself. Any
typos blame the phone.

**Comment by Urmel** [comment]
Hi @nemethviktor,
for sure that's ok!
BR
Alex

**Comment by nemethviktor** [comment]
Sigh - stupid VS2022 doesn't have built-in Pull Request Merge capabilities. Apparently MS took it out after VS2019. I'll do it manually lol. FML.

**Comment by nemethviktor** [comment]
...Getting there. 
Not pushed it yet but works now. Btw I'll do a "code cleanup" while at it so some of the naming and minor things might change.

**Comment by nemethviktor** [comment]
Right, me again. 
Pushed the update https://github.com/nemethviktor/GeoTagNinja/commit/e1a7dcc00cde60c3cfce9c5973307f2f3181e11b 
May I suggest the followings:
- I'll set up a new branch (dev), we can use that one :) - I actually should have done that a while ago.
 
Particular to the sorting:
- Folders, ".." and drives should probably always come at the top. 
- (I think?) The sorter parses files when entering a folder. This isn't entirely logical because the first thing is that the program lists all the files, which, at that point don't yet have tag properties (e.g. say "Altitude"), however it seems to slow down the whole thing because it's trying anyway. Same on "refresh [F5]". Is there a way to disable sort while reading files and then sort as a one-off once that's complete?
- There's a bool HelperStatic.FileListBeingUpdated that could be used to keep an eye on this above. (ie don't do anything while that's True).

**Comment by Urmel** [comment]
Hi @nemethviktor,

cool thanks. Yes - good idea with the DEV branch :)

Regarding above topics...

**Folders, ".." and drives should probably always come at the top**
You mean that whatever column, we sort by, we should keep folders and ".." at the top (and in alphabetical order)?
I like the idea....

**The sorter parses files when entering a folder**
Hmmm - I guess the list view triggers a sorting as soon as a new item is entered / updated. Which in general makes sense. I actually doubt that the performance decrease is significant, as we are talking about some comparisons with a couple of method invokations. Most of the time I guess is due to process invokation for EXIF ...

I don't see a way to use your status flag, as the sorting automatically gets triggered...
Setting the sortorder to SortOrder.None does not help either - the compare method still gets called on F5. So I'll set the sorter to NULL at the beginning of 'lvwFileList_LoadOrUpdate' and set it to the actual sorter afterwards again (and trigger a sort).

**Comment by Urmel** [comment]
Regarding general discussion on the dev branch - should we open a generic issue for that? During development - while there is still some way to go that might be easier than opening an issue for every little thing...

**Comment by Urmel** [comment]
Hi @nemethviktor,
do you have a hint on how I can get my hand on the model (in the sense of MVC) behind the list view? So that I can query it whether it's a directory or a file (maybe extend it to keep that info). Going further away from the UI, I havn't got a clearer picture how things are working together, yet ...
Thanks!

**Comment by nemethviktor** [comment]
Hi @Urmel 

Just a relatively quick reply -- I've now enabled "discussions" -> https://github.com/nemethviktor/GeoTagNinja/discussions -> we can start/continue there?

Re: > You mean that whatever column, we sort by, we should keep folders and ".." at the top (and in alphabetical order)?
Yup.

Re your last Q re MVP, I don't have an MVP per se, not the least because - as I said above someplace - my background isn't actually coding at all. So I had to look up what "MVP" was :D - says a lot. 
But I'll set up a more prose-based explanation in the Wiki of what the code does in plain(er) English. If you want later you can make an MVP and that can be added. 

ps. I'm usually AFK most of the weekends from about midday Sat till end of Sunday.

**Comment by nemethviktor** [comment]
@Urmel hello -> technical wiki in prose: https://github.com/nemethviktor/GeoTagNinja/wiki/Welcome-To-GeoTagNinja

Feel free to use the discussions feature and I'll reply to any Qs prob on Monday.

**Comment by Urmel** [comment]
Hi @nemethviktor,

> my background isn't actually coding at all. So I had to look up what "MVP" was :D - says a lot.

Respect - for someone with no background on programming, you achieved a whole lot. Just to mention using async calls.

> ps. I'm usually AFK most of the weekends from about midday Sat till end of Sunday.

> Feel free to use the discussions feature and I'll reply to any Qs prob on Monday.

That sounds like you do spend a lot of time on this project - thank you. I have no fixed days and time budget. It all depends. So please do not expect me to reply within a day ;)

**Comment by nemethviktor** [comment]
> Respect - for someone with no background on programming, you achieved a whole lot. Just to mention using async calls.

Tbh I like to sit in the shadows and wait for the world to do things but nobody seems to have stepped up with regards to producing a useful alternative for GeoSetter once it was very obviously coming its end-of-life. The few things I've tried were....unsatisfactory. So, my mindset is a bit like "seriously, how difficult can it be?!" (where "it" is anything within reason.) -> my background is SQL development and I can get away with VBA, which, let's face it is far from anything vaguely modern. But I started in June and got something going by 1st August (first public release.). Still, learning C# this way is a lot more fun than doing stupid books and fake udemy courses.

> That sounds like you do spend a lot of time on this project - thank you.

My day-job is a mix of busy and less-so. I won't incriminate myself but there appear to be gaps in my busy-ness here and there. Infer what you wish ;) - at the same time I have no expectations from anyone else to spend time on this. If they do, I'm thankful for it, espc if they appear to be more knowledgeable about coding than I am, which isn't particularly difficult. At least I might learn something new. Beyond that, the whole thing is a pet project.

**Pull request merged**
