### PR TITLE
Encapsulate dirty DE detection

### PR DESCRIPTION
**Pull request by Urmel**
Started to create PR for things done so far....

### CODE REVIEW

**Comment by nemethviktor** [comment]
Hey, thanks for that -- I've merged it, but wrt the inefficient part, I'm thinking it'd be easier to create and maintain that hashset on the fly? Like when any value gets added to the DE3-stage (via `SetAttributeValue` or `SetAttributeValueAnyType` then add to the HS and when going through `RemoveAttributeValue` then remove?

**Comment by Urmel** [comment]
> t'd be easier to create and maintain that hashset on the fly? Like when any value

That could work, but you would need to maintain the set on DE + Attribute + pot. even Version level, I would guess? This set would need to be maintained on DE level (not collection) in order to allow changes to the DEs themselfes.

**Comment by nemethviktor** [comment]
Why though? In the current `HasDirtyAttributes` you're only looking for items that is/has `DirectoryElement.AttributeVersion.Stage3ReadyToWrite`. How's that different from modifying overall logic as such: (simplified)
```
HashSet<string> uids = new HashSet<string>();

public void SetAttributeValueAnyType(ElementAttribute attribute,
                                         string value,
                                         AttributeVersion version,
                                         bool isMarkedForDeletion)
    {
       // leave existing code as-is
       // add:
       if(version == DirectoryElement.AttributeVersion.Stage3ReadyToWrite)
              {
                     uids.Add(DE.GUID) // it's called something else but you see my point
              }
       }
// same for SetAttributeValue
// generally apply same logic for RemoveAttributeValue just deduct it from the Set
}
```

**Comment by nemethviktor** [comment]
Sorry I'm a bit confused now. The idea to separate dirty was coming from you, and so i'm assuming you had something specific on your mind ;) - i.e. you initially introduced that values in `Stage3ReadyToWrite`  in particular should be accounted for, yesno? I'm just following your logic and suggested what might be an easier way around. 

Nonetheless only items in `Stage3ReadyToWrite` do get to be written upon saving as the that _is_ the write-queue.

`RemoveAttributeValue` is specific to version so if the queue gets cleared w/o saving those get deleted. You could try and see if it does what you were after :)

**Comment by Urmel** [comment]
:) Could have just looked into DirectoryElement.HasDirtyAttributes....

I guess implementing this on DE level would be a good trade off. We improve by not having to scan all attributes of an item. But we still support an item (DE) to be in more than one collection. Furthermore modifying the collection from an element feels like breaking encapsulation.

One question remains: Do we have the possibility that an item gets "clean" again without pushing the save button (ie. like "revert all changes to this item" / undo)? I'm not aware of it...

**Comment by nemethviktor** [comment]
> One question remains: Do we have the possibility that an item gets "clean" again without pushing the save button (ie. like "revert all changes to this item" / undo)? I'm not aware of it...

Yes, of course, should the user refresh the folder and then choose "no" to save. It's done by `internal static async Task FsoCheckOutstandingFiledataOkayToChangeFolderAsync` at a "mass" level but at the moment there is no way to do just that for individual DEs, though it would be easy to do.

**Comment by Urmel** [comment]
Ok - so we do not need to consider individual attributes to be reverted at the moment.
Shall I push an update also to the big PR https://github.com/nemethviktor/GeoTagNinja/pull/85?

**Comment by nemethviktor** [comment]
Sure thing
Thanks ;)

**Pull request merged**
