### PR TITLE
Factored Out Preview Image Component, Created Column Show/Hide Selection

### PR DESCRIPTION
**Pull request by Urmel**
Factored Preview Image Component
* Created component ImagePreview that can also display text
* Replaced image preview component on main form
* Added basic error message in HelperStatic.lvwFileList.cs
* MouseUp and KeyUp now use same method for updating map and preview

Column Show/Hide Selection (modal form)
* New form to select which cols to hide/show
* Adapted col setting loading (no more decision on col names)
* Added context menu to FileList to open col selection
* Removed "-2" for col width

Localization:
* Static ref variant to FrmMain did not work - changed to Application.OpenForms for FrmEditFileData, FrmImportGpx, HelperStatic.Generic
* Factored out public Property FrmMain.ApplicationLanguage
* Added localization in EN and to be translated fields in FR

Open:
* Localization of context menu does not work

Signed-off-by: Alexander Behring <alex@behrings.eu>

### CODE REVIEW

**Comment by Urmel** [comment]
Will rebase...

**Comment by nemethviktor** [comment]
Thanks, will have a look once reworked :)
Btw I'm currently reworking the fileEditFrm and the code behind it. Found why it's sooo slow. 
Afterwards (not now) will have a look at the Language stuff so we use CSV rather than SQLITE. Easier to refactor/amend.

**Comment by nemethviktor** [comment]
Right, just pushed a changeset - I promise not to poke the code till at least the morning. 
The next current step is to replace all the datatable logic with what's been introduced in this change in Edit.

**Comment by Urmel** [comment]
Hi @nemethviktor,
I finally got to rebasing / merging this stuff....

There are two open points...

### Handling of non-image files
In the event handler, one can find this piece of code:

>             // for folders and other non-valid items, don't do anything.
>             if (HelperStatic.HsMapMarkers.Count > 0)
>             {
>                 NavigateMapGo();
>                 // pbx_imagePreview.Image = null;
>             }

You note the commented out part - from the comment above the if, I would infer that for normal image files, the code is not called. But it is... Therefore, I commented out the nulling of the image. But we do need it for folders in order to not show an image.

### Localization of context menu does not work

The context menu of the list view does not show the text loaded from the DB and set to the control. For other controls, it works just fine.... but not for this one. Tests with only a single word and no spaces, other chars, ... -> no success.

Any ideas?


## Localization

I'm not sure of I did this right - I just added the new lines to the db files...

> INSERT INTO "main"."CheckBox" ("objectName", "actionType", "objectText") VALUES ('cb_DeSelectAll', NULL, '(Un)Check All');
> INSERT INTO "main"."Label" ("objectName", "actionType", "objectText") VALUES ('lbl_SelectColsTitle', NULL, 'Select Columns');
> INSERT INTO "main"."PictureBox" ("objectName", "actionType", "objectText") VALUES ('pbx_imagePreview', 'EmptyText', 'No image to show');
> INSERT INTO "main"."PictureBox" ("objectName", "actionType", "objectText") VALUES ('pbx_imagePreview', 'CouldNotRetrieve', 'Could not retrieve/generate image preview');
> INSERT INTO "main"."ToolStripMenuItem" ("objectName", "actionType", "objectText") VALUES ('tmi_ShowHideCols', NULL, 'Show or Hide Columns');

**Comment by Urmel** [comment]
> Btw I'm currently reworking the fileEditFrm and the code behind it. Found why it's sooo slow.
> Afterwards (not now) will have a look at the Language stuff so we use CSV rather than SQLITE. Easier to refactor/amend.

Let me throw in that Visual Studio comes with a localization mechanism. Obviously the draw back is that one needs to have VS, but if you use that, no more bothering with loading stuff for icons or text fields. Custom messages of course need to be handled in code. But all UI stuff - not.

**Comment by nemethviktor** [comment]
> > Btw I'm currently reworking the fileEditFrm and the code behind it. Found why it's sooo slow.
> > Afterwards (not now) will have a look at the Language stuff so we use CSV rather than SQLITE. Easier to refactor/amend.
> 
> Let me throw in that Visual Studio comes with a localization mechanism. Obviously the draw back is that one needs to have VS, but if you use that, no more bothering with loading stuff for icons or text fields. Custom messages of course need to be handled in code. But all UI stuff - not.

Will reply to the comment above (before this) in a moment but yeah it comes with localisation, except I learnt it a bit late :D - so hence I started doing things in sqlite. I don't quite mind how it's done but part of the idea in the longer term is that people can help themselves/the project to do it. E.g. I don't speak French or German and at this point the only way for anyone to add localisation is to modify the Excel file and dump a sqlite update. This isn't particularly great but most people have Excel. Eventually I think a CSV file might be a little easier to track and merge.

**Comment by Urmel** [comment]
Stupid me ...  the text cannot be correct if I overwrite it a few lines later ... ahhhh... maybe too late....

**Comment by nemethviktor** [comment]
> maybe too late....
Nah. I'm watching Star Wars Andor atm. Will deal w/ the code tomo ;) -- feel free to nudge it any way you'd like. :)

**Pull request merged**
